"""Centralized roles, account statuses, and permissions (User Management V2).

Do not scatter `if role == "SUPERVISOR"` checks — use ROLE_PERMISSIONS
and the `require_permission` / `require_roles` dependencies instead.
"""
from __future__ import annotations

# --- Roles (closed set; LAB_ANALYST intentionally removed from active UI) ---
ROLE_SUPERADMIN = "SUPERADMIN"
ROLE_ADMIN = "ADMIN"
ROLE_SUPERVISOR = "SUPERVISOR"
ROLE_VENDOR = "VENDOR"
# Read-only oversight: sees every admin view + audit logs, cannot change anything.
ROLE_MONITOR = "MONITOR"

VALID_ROLES = {ROLE_SUPERADMIN, ROLE_ADMIN, ROLE_SUPERVISOR, ROLE_VENDOR, ROLE_MONITOR}

# --- Account lifecycle (distinct from role) ---
ACCOUNT_INVITED = "INVITED"
ACCOUNT_ACTIVE = "ACTIVE"
ACCOUNT_SUSPENDED = "SUSPENDED"
ACCOUNT_DEACTIVATED = "DEACTIVATED"

VALID_ACCOUNT_STATUSES = {
    ACCOUNT_INVITED,
    ACCOUNT_ACTIVE,
    ACCOUNT_SUSPENDED,
    ACCOUNT_DEACTIVATED,
}

# --- Invitation lifecycle ---
INVITE_PENDING = "PENDING"
INVITE_SENT = "SENT"
INVITE_ACCEPTED = "ACCEPTED"
INVITE_EXPIRED = "EXPIRED"
INVITE_REVOKED = "REVOKED"

VALID_INVITATION_STATUSES = {
    INVITE_PENDING,
    INVITE_SENT,
    INVITE_ACCEPTED,
    INVITE_EXPIRED,
    INVITE_REVOKED,
}

# --- Project assignment lifecycle ---
ASSIGN_PENDING = "PENDING"
ASSIGN_ACTIVE = "ACTIVE"
ASSIGN_COMPLETED = "COMPLETED"
ASSIGN_CANCELLED = "CANCELLED"
ASSIGN_REMOVED = "REMOVED"

VALID_ASSIGNMENT_STATUSES = {
    ASSIGN_PENDING,
    ASSIGN_ACTIVE,
    ASSIGN_COMPLETED,
    ASSIGN_CANCELLED,
    ASSIGN_REMOVED,
}

# --- Vendor lifecycle ---
VENDOR_PROSPECT = "PROSPECT"
VENDOR_ACTIVE = "ACTIVE"
VENDOR_SUSPENDED = "SUSPENDED"
VENDOR_BLACKLISTED = "BLACKLISTED"

VALID_VENDOR_STATUSES = {
    VENDOR_PROSPECT,
    VENDOR_ACTIVE,
    VENDOR_SUSPENDED,
    VENDOR_BLACKLISTED,
}

# --- Reference service categories (configurable; not exhaustive) ---
SERVICE_CATEGORIES = {
    "GEOTECHNICAL_INVESTIGATION",
    "SOIL_TESTING",
    "SURVEYING",
    "DRILLING",
    "MATERIAL_TESTING",
    "CIVIL_WORKS",
    "EQUIPMENT_RENTAL",
    "TRANSPORTATION",
    "LABOR_SUPPLY",
    "ENGINEERING_CONSULTANCY",
}

# --- RFQ / quotation / work-order lifecycles ---
RFQ_DRAFT = "DRAFT"
RFQ_SENT = "SENT"
RFQ_EVALUATING = "EVALUATING"
RFQ_AWARDED = "AWARDED"
RFQ_CLOSED = "CLOSED"
RFQ_CANCELLED = "CANCELLED"

VALID_RFQ_STATUSES = {
    RFQ_DRAFT, RFQ_SENT, RFQ_EVALUATING, RFQ_AWARDED, RFQ_CLOSED, RFQ_CANCELLED,
}

RFQ_VENDOR_SENT = "SENT"
RFQ_VENDOR_VIEWED = "VIEWED"
RFQ_VENDOR_DECLINED = "DECLINED"
RFQ_VENDOR_SUBMITTED = "QUOTATION_SUBMITTED"
RFQ_VENDOR_EXPIRED = "EXPIRED"

VALID_RFQ_VENDOR_STATUSES = {
    RFQ_VENDOR_SENT, RFQ_VENDOR_VIEWED, RFQ_VENDOR_DECLINED,
    RFQ_VENDOR_SUBMITTED, RFQ_VENDOR_EXPIRED,
}

QUOTATION_DRAFT = "DRAFT"
QUOTATION_SUBMITTED = "SUBMITTED"
QUOTATION_SUPERSEDED = "SUPERSEDED"
QUOTATION_EVALUATED = "EVALUATED"
QUOTATION_AWARDED = "AWARDED"
QUOTATION_REJECTED = "REJECTED"

VALID_QUOTATION_STATUSES = {
    QUOTATION_DRAFT, QUOTATION_SUBMITTED, QUOTATION_SUPERSEDED,
    QUOTATION_EVALUATED, QUOTATION_AWARDED, QUOTATION_REJECTED,
}

WO_DRAFT = "DRAFT"
WO_IN_REVIEW = "IN_REVIEW"
WO_PDF_GENERATED = "PDF_GENERATED"
WO_SIGNED = "SIGNED"
WO_STAMPED = "STAMPED"
WO_FINALIZED = "FINALIZED"
WO_ISSUED = "ISSUED"
WO_VIEWED = "VIEWED"
WO_ACCEPTED = "ACCEPTED"
WO_REJECTED = "REJECTED"
WO_CANCELLED = "CANCELLED"
WO_IN_PROGRESS = "IN_PROGRESS"
WO_COMPLETED = "COMPLETED"
WO_CLOSED = "CLOSED"

VALID_WO_STATUSES = {
    WO_DRAFT, WO_IN_REVIEW, WO_PDF_GENERATED, WO_SIGNED, WO_STAMPED,
    WO_FINALIZED, WO_ISSUED, WO_VIEWED, WO_ACCEPTED, WO_REJECTED,
    WO_CANCELLED, WO_IN_PROGRESS, WO_COMPLETED, WO_CLOSED,
}

WO_TRANSITIONS: dict[str, set[str]] = {
    # Professional sign/stamp branch (new) + direct issue kept for backward compat.
    WO_DRAFT: {WO_IN_REVIEW, WO_PDF_GENERATED, WO_ISSUED, WO_CANCELLED},
    WO_IN_REVIEW: {WO_PDF_GENERATED, WO_DRAFT, WO_CANCELLED},
    WO_PDF_GENERATED: {WO_SIGNED, WO_DRAFT, WO_CANCELLED},
    WO_SIGNED: {WO_STAMPED, WO_CANCELLED},
    WO_STAMPED: {WO_FINALIZED, WO_CANCELLED},
    WO_FINALIZED: {WO_ISSUED, WO_CANCELLED},
    WO_ISSUED: {WO_VIEWED, WO_ACCEPTED, WO_REJECTED, WO_CANCELLED},
    WO_VIEWED: {WO_ACCEPTED, WO_REJECTED, WO_CANCELLED},
    WO_ACCEPTED: {WO_IN_PROGRESS, WO_CANCELLED},
    WO_REJECTED: set(),
    WO_IN_PROGRESS: {WO_COMPLETED, WO_CANCELLED},
    WO_COMPLETED: {WO_CLOSED},
    WO_CANCELLED: set(),
    WO_CLOSED: set(),
}

# --- Project lifecycle ---
PROJECT_DRAFT = "DRAFT"
PROJECT_PLANNED = "PLANNED"
PROJECT_ACTIVE = "ACTIVE"
PROJECT_ON_HOLD = "ON_HOLD"
PROJECT_COMPLETED = "COMPLETED"
PROJECT_CLOSED = "CLOSED"
PROJECT_CANCELLED = "CANCELLED"

VALID_PROJECT_STATUSES = {
    PROJECT_DRAFT, PROJECT_PLANNED, PROJECT_ACTIVE, PROJECT_ON_HOLD,
    PROJECT_COMPLETED, PROJECT_CLOSED, PROJECT_CANCELLED,
}

PROJECT_TRANSITIONS: dict[str, set[str]] = {
    PROJECT_DRAFT: {PROJECT_PLANNED, PROJECT_CANCELLED},
    PROJECT_PLANNED: {PROJECT_ACTIVE, PROJECT_CANCELLED},
    PROJECT_ACTIVE: {PROJECT_ON_HOLD, PROJECT_COMPLETED, PROJECT_CANCELLED},
    PROJECT_ON_HOLD: {PROJECT_ACTIVE, PROJECT_CANCELLED},
    PROJECT_COMPLETED: {PROJECT_CLOSED},
    PROJECT_CLOSED: set(),
    PROJECT_CANCELLED: set(),
}

# --- Expenditure lifecycle + categories ---
EXP_DRAFT = "DRAFT"
EXP_SUBMITTED = "SUBMITTED"
EXP_APPROVED = "APPROVED"
EXP_REJECTED = "REJECTED"

VALID_EXP_STATUSES = {EXP_DRAFT, EXP_SUBMITTED, EXP_APPROVED, EXP_REJECTED}

EXP_CATEGORIES = {
    "MATERIAL",
    "LABOR",
    "EQUIPMENT",
    "FUEL",
    "TRANSPORT",
    "VENDOR",
    "SUBCONTRACT",
    "SITE_EXPENSE",
    "MISCELLANEOUS",
}

# --- DER lifecycle ---
DER_DRAFT = "DRAFT"
DER_SUBMITTED = "SUBMITTED"

VALID_DER_STATUSES = {DER_DRAFT, DER_SUBMITTED}
EMPLOYMENT_TYPES = {"FULL_TIME", "PART_TIME", "CONTRACT", "CONSULTANT", "TEMPORARY"}
PROFICIENCIES = {"BEGINNER", "INTERMEDIATE", "ADVANCED", "EXPERT"}
CERT_STATUSES = {"ACTIVE", "EXPIRED", "REVOKED"}
SUPERVISOR_SPECIALIZATIONS = {
    "SOIL_INVESTIGATION",
    "ROCK_INVESTIGATION",
    "BOREHOLE_DRILLING",
    "CORE_DRILLING",
    "SPT",
    "SAMPLING",
    "SITE_SUPERVISION",
    "QUALITY_CONTROL",
    "SAFETY",
}

# --- Permissions (foundation; extend for Vendor/RFQ/WorkOrder later) ---
USER_VIEW = "USER_VIEW"
USER_CREATE = "USER_CREATE"
USER_UPDATE = "USER_UPDATE"
USER_INVITE = "USER_INVITE"
USER_DISABLE = "USER_DISABLE"
USER_DELETE = "USER_DELETE"
ROLE_CHANGE = "ROLE_CHANGE"

PROJECT_VIEW = "PROJECT_VIEW"
PROJECT_CREATE = "PROJECT_CREATE"
PROJECT_UPDATE = "PROJECT_UPDATE"
PROJECT_ASSIGN = "PROJECT_ASSIGN"

DER_CREATE = "DER_CREATE"
DER_VIEW = "DER_VIEW"
DER_UPDATE = "DER_UPDATE"
DER_REVIEW = "DER_REVIEW"

EXPENDITURE_CREATE = "EXPENDITURE_CREATE"
EXPENDITURE_VIEW = "EXPENDITURE_VIEW"
EXPENDITURE_REVIEW = "EXPENDITURE_REVIEW"
EXPENDITURE_APPROVE = "EXPENDITURE_APPROVE"

VENDOR_VIEW = "VENDOR_VIEW"
VENDOR_CREATE = "VENDOR_CREATE"
VENDOR_UPDATE = "VENDOR_UPDATE"
VENDOR_DELETE = "VENDOR_DELETE"
VENDOR_STATUS = "VENDOR_STATUS"

RFQ_CREATE = "RFQ_CREATE"
RFQ_SEND = "RFQ_SEND"
RFQ_VIEW = "RFQ_VIEW"
RFQ_CLOSE = "RFQ_CLOSE"

QUOTATION_SUBMIT = "QUOTATION_SUBMIT"
QUOTATION_VIEW = "QUOTATION_VIEW"
QUOTATION_REVIEW = "QUOTATION_REVIEW"

EVALUATION_CREATE = "EVALUATION_CREATE"
AWARD_CREATE = "AWARD_CREATE"

WORK_ORDER_CREATE = "WORK_ORDER_CREATE"
WORK_ORDER_ISSUE = "WORK_ORDER_ISSUE"
WORK_ORDER_VIEW = "WORK_ORDER_VIEW"
WORK_ORDER_ACCEPT = "WORK_ORDER_ACCEPT"
WORK_ORDER_SIGN = "WORK_ORDER_SIGN"
WORK_ORDER_STAMP = "WORK_ORDER_STAMP"
WORK_ORDER_FINALIZE = "WORK_ORDER_FINALIZE"
WORK_ORDER_PDF = "WORK_ORDER_PDF"

PROJECT_VENDOR_ASSIGN = "PROJECT_VENDOR_ASSIGN"

ROLE_PERMISSIONS: dict[str, set[str]] = {
    ROLE_SUPERADMIN: {
        USER_VIEW, USER_CREATE, USER_UPDATE, USER_INVITE, USER_DISABLE,
        USER_DELETE, ROLE_CHANGE,
        PROJECT_VIEW, PROJECT_CREATE, PROJECT_UPDATE, PROJECT_ASSIGN,
        DER_CREATE, DER_VIEW, DER_UPDATE, DER_REVIEW,
        EXPENDITURE_CREATE, EXPENDITURE_VIEW, EXPENDITURE_REVIEW, EXPENDITURE_APPROVE,
        VENDOR_VIEW, VENDOR_CREATE, VENDOR_UPDATE, VENDOR_DELETE, VENDOR_STATUS,
        RFQ_CREATE, RFQ_SEND, RFQ_VIEW, RFQ_CLOSE,
        QUOTATION_SUBMIT, QUOTATION_VIEW, QUOTATION_REVIEW,
        EVALUATION_CREATE, AWARD_CREATE,
        WORK_ORDER_CREATE, WORK_ORDER_ISSUE, WORK_ORDER_VIEW, WORK_ORDER_ACCEPT,
        WORK_ORDER_SIGN, WORK_ORDER_STAMP, WORK_ORDER_FINALIZE, WORK_ORDER_PDF,
        PROJECT_VENDOR_ASSIGN,
    },
    ROLE_ADMIN: {
        USER_VIEW, USER_CREATE, USER_UPDATE, USER_INVITE, USER_DISABLE,
        ROLE_CHANGE,
        PROJECT_VIEW, PROJECT_CREATE, PROJECT_UPDATE, PROJECT_ASSIGN,
        DER_CREATE, DER_VIEW, DER_UPDATE, DER_REVIEW,
        EXPENDITURE_CREATE, EXPENDITURE_VIEW, EXPENDITURE_REVIEW, EXPENDITURE_APPROVE,
        VENDOR_VIEW, VENDOR_CREATE, VENDOR_UPDATE, VENDOR_STATUS,
        RFQ_CREATE, RFQ_SEND, RFQ_VIEW, RFQ_CLOSE,
        QUOTATION_VIEW, QUOTATION_REVIEW,
        EVALUATION_CREATE, AWARD_CREATE,
        WORK_ORDER_CREATE, WORK_ORDER_ISSUE, WORK_ORDER_VIEW,
        WORK_ORDER_SIGN, WORK_ORDER_STAMP, WORK_ORDER_FINALIZE, WORK_ORDER_PDF,
        PROJECT_VENDOR_ASSIGN,
    },
    ROLE_SUPERVISOR: {
        USER_VIEW,
        PROJECT_VIEW,
        DER_CREATE, DER_VIEW, DER_UPDATE,
        EXPENDITURE_CREATE, EXPENDITURE_VIEW,
        WORK_ORDER_VIEW,
    },
    ROLE_VENDOR: {
        USER_VIEW,
        PROJECT_VIEW,
        VENDOR_VIEW,
        RFQ_VIEW,
        QUOTATION_SUBMIT, QUOTATION_VIEW,
        WORK_ORDER_VIEW, WORK_ORDER_ACCEPT,
    },
    # View-only oversight (no create/update/approve/delete anywhere).
    ROLE_MONITOR: {
        USER_VIEW,
        PROJECT_VIEW,
        DER_VIEW,
        EXPENDITURE_VIEW,
        VENDOR_VIEW,
        RFQ_VIEW,
        QUOTATION_VIEW,
        WORK_ORDER_VIEW, WORK_ORDER_PDF,
    },
}


def normalize_role(role: str | None) -> str:
    if not role:
        return ""
    return role.strip().replace(" ", "").upper()


def permissions_for(role: str | None) -> set[str]:
    return set(ROLE_PERMISSIONS.get(normalize_role(role), set()))


def has_permission(role: str | None, permission: str) -> bool:
    return permission in permissions_for(role)
